### ISSUE TITLE
Money Weight/Error Buying

### ISSUE THREAD

**Issue by dtoxic47** [phyreman/ZConomy#4]
Ok so if for some reason the weight of the money is bellow 0.05 (i think weight is how much money "buying power you have") then errors pop up when right clicking on vending machines

Here is the Log portion

<details><summary>LOG</summary>function: initWorldContextMenu -- file: ZConomyContextMenu.lua line # 161 | MOD: ZConomy
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@76756b3e
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 484 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 369 | Vanilla

LOG  : General     , 1665324807117> __le not defined for operand
LOG  : General     , 1665324807258> creating new sourcewindow: E:/Games HDD/PZ_Test/Saves/mods/ZConomy/media/lua/client/UI/ZConomyContextMenu.lua
ERROR: General     , 1665324815749> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: __le not defined for operand at KahluaUtil.fail line:82.
ERROR: General     , 1665324815749> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: __le not defined for operand
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:900)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3064)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.ui.UIManager.update(UIManager.java:931)
	at zombie.GameWindow.logic(GameWindow.java:261)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:764)
	at zombie.GameWindow.run_ez(GameWindow.java:680)
	at zombie.GameWindow.mainThread(GameWindow.java:494)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1665324815751> -----------------------------------------
</details>

A solution would be to add some kind of a code to tell the user that he has not enough money to buy snacks/pop if the "weight" is not enough for buying?!

To test this start PZ in debug mode and add a single "Money" item witch weighs 0.01 then try to buy something and you will get the error

If you need any more info just let me know

**Comment by dtoxic47** [comment]
Here is another bug (i wont open another issue as it's similar to the previous one) This time right-clicking on crops (to harvest etc...) shows a red box

<details><summary>LOG</summary>LOG  : General     , 1665508217423> -----------------------------------------
STACK TRACE
-----------------------------------------
function: initWorldContextMenu -- file: ZConomyContextMenu.lua line # 31 | MOD: ZConomy
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@e65d047d
function: createMenu -- file: ISWorldObjectContextMenu.lua line # 484 | Vanilla
function: createMenu -- file: ISMenuContextWorld.lua line # 50 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: doRClick -- file: ISObjectClickHandler.lua line # 60 | Vanilla
function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 369 | Vanilla

ERROR: General     , 1665508217435> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: find of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1665508217435> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: find of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:228)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:3064)
	at jdk.internal.reflect.GeneratedMethodAccessor769.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:79)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.ui.UIManager.update(UIManager.java:931)
	at zombie.GameWindow.logic(GameWindow.java:261)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:764)
	at zombie.GameWindow.run_ez(GameWindow.java:680)
	at zombie.GameWindow.mainThread(GameWindow.java:494)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1665508217437> -----------------------------------------
STACK TRACE</details>
